configfile:
    "config_files/config.yaml"

sample_ids, = glob_wildcards(config['assemblies']+"/{sample}.fasta")

print(config['assemblies'])
print(sample_ids)

rule all:
    input:
        expand(config['output']+"/PSout/{sample}.out", sample=sample_ids),
        "Phylosift.tree"

rule phylosift:
    input:
        config['assemblies']+"/{sample}.fasta",
    output:
        directory(config['output']+"/PSout/{sample}.out")
    shell:
        """
        ~/Data/PhyloSift/bin/phylosift search --debug --threads 64 --debug --isolate --besthit --output {output} {input}
        ~/Data/PhyloSift/bin/phylosift  align --debug --threads 64 --debug --isolate --besthit --output {output} {input}
        """

rule phylosift_process:
    output:
        "Phylosift.tree"
    shell:
        """
        cat PSout/*/alignDir/concat.updated.1.fasta > concat_PS.fasta
        perl -p -i -e "s/\.fasta.+//g" concat_PS.fasta
        ~/Data/PhyloSift/bin/FastTree <concat_PS.fasta> Phylosift.tree
        """
