import re
import os

configfile:
    "config/config.yaml"

sample_ids, = glob_wildcards(config['read_path']+"/{sample}.R1.fastq.gz")
ref, = glob_wildcards(config['ref_path']+"/{reference}.fa")

print(sample_ids)
print(ref)

rule all:
    input:
        expand(config['ref_path']+"/{reference}.fa.amb", reference = ref),
        expand(config['output']+"/sorted_reads/{reference}/{sample}.bam", sample=sample_ids, reference=ref),
        expand(config['output']+"/Coverage_files/{reference}/{sample}_coverage.txt", sample=sample_ids, reference=ref),
        expand(config['output']+"/{reference}_hclust.pdf", reference=ref)


rule index_ref:
    input:
        config['ref_path']+"/{reference}.fa"
    output:
        config['ref_path']+"/{reference}.fa.amb"
    priority: 10
    conda:
        "config/plasmidlord.yaml"
    shell:
        "bwa index {input}"
        
rule bwa_map:
    input:
        ref = config['ref_path']+"/{reference}.fa",
        r1 = config['read_path']+"/{sample}.R1.fastq.gz",
        r2 = config['read_path']+"/{sample}.R2.fastq.gz"
    output:
        config['output']+"/sorted_reads/{reference}/{sample}.bam"
    priority:9
    log: 
        "logs/bwa_mem/{reference}/{sample}.log"
    conda: 
        "config/plasmidlord.yaml"
    shell:
        "bwa mem {input.ref} {input.r1} {input.r2} | samtools view -ubS -F 0x904 - | samtools sort -o {output}"


rule samtools_depth:
    input:
        config['output']+"/sorted_reads/{reference}/{sample}.bam"
    output:
        config['output']+"/Coverage_files/{reference}/{sample}_coverage.txt"
    priority:7
    conda: 
        "config/plasmidlord.yaml"
    shell:
        "samtools depth {input} > {output}"


rule heatmap:
    output:
        config['output']+"/{reference}_hclust.pdf"
    conda:
        "config/plasmidlord.yaml"
    params:
        bins = config['bin_size'],
        tick = config['tick_size'],
        out = config['output']
    priority: 0
    shell:
        "python2 plasmidlord.py -b {params.bins} -t {params.tick} {params.out}/Coverage_files/{wildcards.reference} {params.out}/{wildcards.reference}"





